info.component: RabbitMQ (amqp) Enge Client

management.health.binders.enabled: true

server.port: ${PORT:${SERVER_PORT:8001}}

# http://docs.spring.io/spring-cloud-stream/docs/1.0.0.RC1/reference/htmlsingle/index.html#_kafka_binder_properties
spring:

  rabbitmq:
    host: ${DOCKER_HOST:192.168.99.100}
    addresses: ${DOCKER_HOST:192.168.99.100}:5672
  cloud:
    stream:
      rabbit:
        binder:
          addresses: ${DOCKER_HOST:192.168.99.100}:5672
      bindings:
        output:
          destination: messages

  zipkin.baseUrl: ${ZIPKIN_URL:http://${ZIPKIN_HOST:${DOCKER_HOST:192.168.99.100}}:${ZIPKIN_PORT:9411}}
